# Generated by Django 3.1.7 on 2021-03-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('unit', models.CharField(max_length=128)),
                ('ref_range', models.CharField(max_length=128)),
                ('finding', models.CharField(max_length=1)),
                ('result_state', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PatientLab',
            fields=[
                ('id_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField(null=True)),
                ('lab_number', models.CharField(max_length=128)),
                ('clinic_code', models.CharField(max_length=128)),
                ('date_of_test', models.DateTimeField()),
                ('mobile_phone', models.CharField(max_length=16)),
            ],
        ),
    ]
