# Generated by Django 3.1.7 on 2021-03-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210321_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlab',
            name='mobile_phone',
            field=models.CharField(default='-', max_length=16),
        ),
    ]
