# Generated by Django 3.1.7 on 2021-03-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210321_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlab',
            name='date_of_birth',
            field=models.CharField(default=True, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientlab',
            name='date_of_test',
            field=models.CharField(max_length=16),
        ),
    ]
